// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tbluser struct {
	IdUser        int32       `json:"idUser"`
	IdRol         int16       `json:"idRol"`
	NameUser      string      `json:"NameUser"`
	Email         string      `json:"Email"`
	LastName      string      `json:"LastName"`
	DateCreated   pgtype.Date `json:"DateCreated"`
	LastActivitie pgtype.Date `json:"LastActivitie"`
	Password      string      `json:"Password"`
}
