// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tbluser struct {
	Iduser        int32       `json:"iduser"`
	Idrol         int16       `json:"idrol"`
	Nameuser      string      `json:"nameuser"`
	Email         string      `json:"email"`
	Lastname      string      `json:"lastname"`
	Datecreated   pgtype.Date `json:"datecreated"`
	Lastactivitie pgtype.Date `json:"lastactivitie"`
	Password      string      `json:"password"`
}
