// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// internal/repository/queries.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (Tbluser, error)
	DeleteUser(ctx context.Context, iduser int32) error
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]Tbluser, error)
	GetUserByEmail(ctx context.Context, email string) (Tbluser, error)
	GetUserByID(ctx context.Context, iduser int32) (Tbluser, error)
	GetUsersWithFilters(ctx context.Context, arg GetUsersWithFiltersParams) ([]Tbluser, error)
}

var _ Querier = (*Queries)(nil)
